name: Release a PRE-release version to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "PRE-release version (without v, without -pre-release)"
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

    - name: Parse semver string
      id: semver_parser 
      uses: booxmedialtd/ws-action-parse-semver@7784200024d6b3fc01253e617ec0168daf603de3 # v1.4.7
      with:
        input_string: ${{ inputs.version }}-pre-release

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@openpass'

    - name: Set version for deploy
      run: npm version "${VERSION}" --no-git-tag-version --allow-same-version
      env:
        VERSION: ${{ steps.semver_parser.outputs.fullversion }}

    - name: NPM Install
      run: npm install --also=dev

    - name: NPM Test
      run: npm test

    - name: Update Git user
      run: |
        git config --local user.name "openpass-sso"
        git config --local user.email openpass-sso@users.noreply.github.com

    - name: Commit version for deploy
      run: |
        git add package.json
        git add package-lock.json
        git commit -m "Releasing version: ${VERSION}"
      env:
        VERSION: ${{ steps.semver_parser.outputs.fullversion }}

    - name: NPM Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create Release Tag
      uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1.7.2
      with:
        tag: "v${{ steps.semver_parser.outputs.fullversion }}"
        message: "Release v${{ steps.semver_parser.outputs.fullversion }}"

    - name: GitHub Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      with:
        generate_release_notes: true
        tag_name: v${{ steps.semver_parser.outputs.fullversion }}
        prerelease: true
